### ISSUE TITLE
과제를 읽고 해야할 것들이 무엇이 있는지 체크리스트 만들기

### ISSUE THREAD

**Issue by woolimi** [woolimi/cloud-1#1]
- [ ] 서버 재부팅 -> 사이트 자동으로 재시작
- [ ] 서버가 재부팅되어도 이미지, 유저, articles 등의 데이터는 그대로
- [ ] 여러 서버들은 배포될때 병렬적으로 실행되어야함
- [ ] 컨테이너 ubuntu 20.04 LTS, SSH daemon, Python 설치되어있어야 함
- [ ] 프로세스당 하나의 컨테이너
- [ ] 외부에서 데이터베이스로 직접 접근 불가
- [ ] WordPress, Phymyadmin, MySQL
- [ ] docker-compose.yml 사용
- [ ] TLS 구현
- [ ] URL에 따라 제대로된 사이트에 접근해야함

**Comment by jeanoza** [comment]
1. 클라우드 환경 준비

- Ubuntu 20.04 LTS
- Python
- SSH
- AWS VS Scaleway

2. Docker 및 Docker Compose 설치

3. 자동화 스크립트 작성 (Ansible)

	- Ansible playook 작성을 통해 다음 작업 자동화

		- Docker 및 Docker compose 설치
		- docker-compose.yml 파일을 사용하여 WordPress, MySQL, PHPMyAdmin 컨테이너를 설정하고 실행
		- 사이트 재부팅 시 자동 재시작 설정
		- 데이터 지속성 보장 (예: WordPress에서 업로드한 이미지나 사용자 데이터가 서버 재부팅 후에도 남아 있어야 함)
		- 보안 설정 (예: MySQL 데이터베이스에 인터넷을 통한 직접 접속 방지)
	SSL/TLS 설정 (HTTPS를 통해 사이트에 접근 가능하도록 설정)

	- ex:
	```yml
	---
	- hosts: all
	become: yes
	tasks:
		- name: Update and install necessary packages
		apt:
			name: ['docker.io', 'docker-compose']
			update_cache: yes
			state: present

		- name: Ensure Docker is started
		service:
			name: docker
			state: started
			enabled: yes

		- name: Create directory for docker-compose
		file:
			path: /opt/wordpress
			state: directory
			mode: '0755'

		- name: Copy docker-compose.yml
		copy:
			src: ./docker-compose.yml
			dest: /opt/wordpress/docker-compose.yml

		- name: Start the containers with Docker Compose
		command: docker-compose up -d
		args:
			chdir: /opt/wordpress

		- name: Configure UFW to allow only SSH, HTTP, and HTTPS
		ufw:
			rule: allow
			port: "{{ item }}"
			proto: tcp
		with_items:
			- 22
			- 80
			- 443

		- name: Enable UFW
		ufw:
			state: enabled

		## let's encrpyt 예시
		- name: Install certbot
		apt:
			name: certbot
			state: present

		- name: Obtain SSL certificate with Let's Encrypt
		command: certbot --nginx -d yourdomain.com -d www.yourdomain.com
	```

4. Docker Compose통해 WordPress, MySQL, Php My Admin 설정

	- Docker Compose 3개 컨테이너 작성
		- WordPress
		- MySQL
		- Php My admin

	- Volume 영속화(서버 재시작 시에도 유지를 위해)
		- wordpress
		- MySQL

	- Docker network
		- Php my admin과 Wordpress가 MySQL 에 접근할수 있도록 설정

5. 보안 및 네트워크 설정

	- UFW : SSH와 HTTPS 외의 불필요한 포트는 닫아야함
		- ex: MySQL 포트는 외부에서 접근하지 못하도록 방화벽으로 보호

	- HTTPS 및 TLS 인증서 설정: Let's Encrypt 같은 도구를 사용하여 SSL 인증서를 설치하고, WordPress 사이트에 HTTPS를 적용

	- 리버스 프록시 설정: Nginx와 같은 리버스 프록시 서버를 설정하여 요청된 URL에 따라 WordPress 또는 PHPMyAdmin으로 redirection

	- Ansible을 이용한

6. Docker Compose 파일 작성

	- docker-compose.yml 파일에 WordPress, MySQL, PHPMyAdmin 등 필요한 모든 서비스에 대한 설정을 포함

	- ex: 
	```yml
	version: '3'

	services:
	db:
		image: mysql:5.7
		volumes:
			- db_data:/var/lib/mysql
		restart: always
		environment:
		MYSQL_ROOT_PASSWORD: example
		MYSQL_DATABASE: wordpress
		MYSQL_USER: wordpress
		MYSQL_PASSWORD: wordpress

	wordpress:
		image: wordpress:latest
		ports:
			- "80:80"
		restart: always
		environment:
		WORDPRESS_DB_HOST: db:3306
		WORDPRESS_DB_USER: wordpress
		WORDPRESS_DB_PASSWORD: wordpress
		WORDPRESS_DB_NAME: wordpress
		volumes:
			- wordpress_data:/var/www/html

	phpmyadmin:
		image: phpmyadmin/phpmyadmin
		restart: always
		ports:
			- "8080:80"
		environment:
		PMA_HOST: db
		MYSQL_ROOT_PASSWORD: example

	volumes:
		db_data:
		wordpress_data:
	```
7. 테스트 및 검증

	- 재부팅 테스트: 인스턴스를 재부팅한 후에도 모든 데이터와 설정이 유지되고, 사이트가 정상적으로 동작하는지 확인합니다.
	- 병렬 배포: 스크립트가 여러 서버에 병렬로 실행될 수 있는지 테스트합니다.(??)
	- 보안 점검: 보안 설정(방화벽, TLS 등)이 제대로 적용되었는지 확인합니다.
8. 최종 결과물
	- 자동화된 배포 스크립트: Ansible 또는 선택한 도구로 작성된 자동화 스크립트.
	- docker-compose.yml 파일: WordPress, MySQL, PHPMyAdmin을 포함한 여러 서비스를 정의한 Docker Compose 파일.
	- 보안 및 지속성 보장: SSL, 방화벽, 데이터 지속성을 포함한 완전한 보안 설정.
